language: go

install:
  - mkdir -p $GOPATH/src/github.com/skyd/sky
  - mv * $GOPATH/src/github.com/skyd/sky
  - pushd $GOPATH/src/github.com/skyd/sky
  - sudo make deps
  - pushd skyd
  - go get
  - popd
  - make
  - sudo make install
  - echo '/usr/local/lib' | sudo tee /etc/ld.so.conf.d/sky.conf
  - sudo ldconfig

script:
  - make test

notifications:
  irc: "irc.freenode.org#skydb"