language: go

install:
  - mkdir -p $GOPATH/src/github.com/skydb/sky
  - mv * $GOPATH/src/github.com/skydb/sky
  - pushd $GOPATH/src/github.com/skydb/sky
  - sudo make deps
  - go get
  - make
  - sudo make install
  - echo '/usr/local/lib' | sudo tee /etc/ld.so.conf.d/sky.conf
  - sudo ldconfig
  

notifications:
  irc:
    channels:
      - "irc.freenode.net#skydb"
    use_notice: true